### ISSUE TITLE
How do you set a custom stickerpack icon?

### ISSUE THREAD

**Issue by SMNFXCN** [apsun/uSticker#29]
No matter what I name it, it always chooses a random sticker as the icon instead,
How do you set a custom icon for each stickerpack?

**Comment by apsun** [comment]
I think it uses the first sticker in the pack. Unfortunately, there is no way currently to configure the order of stickers within packs, so the direct answer to your question is: you can't. This would be a good argument for sorting stickers by name (it would let you pick which sticker came first); historically I chose not to do it because it would cause all existing users to have their stickers reordered, but maybe we can add an option to choose the sorting order as a compromise?

**Comment by SMNFXCN** [comment]
yeah sounds good.

**Comment by apsun** [comment]
Sticker sort order was added as an setting in c5c7567ac99e4446855b14563afe0d60cc82fcb6.
