### ISSUE TITLE
The future?

### ISSUE THREAD

**Issue by ghost** [apsun/uSticker#53]
I loved uSticker but since it is now completely incompatible with Gboard, i was wondering what is going to happen now? 
Will it get updated? Is a second stand-alone app going to get made, or has the project met it's end?

If uStickers journey is over, what alternative could I switch to, since i can't seem to find anything?

**Comment by apsun** [comment]
Since I have switched to an iPhone, maintaining uSticker has kind of fallen to the end of my priority list unfortunately. It's still on my eventual wishlist to make a "uSticker 2.0" as a standalone keyboard, but I can't provide any estimate on when/if that will happen. Regarding an alternative app, see #49.

**Comment by ghost** [comment]
Thanks for your reply! Sad to hear, but fully understandable. Let us know when ever something new arises.

Have a nice day!
